/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.pulgaslocas.gui;

import autonoma.pulgasLocasBase.elements.GraphicContainer;
import autonoma.pulgaslocas.elements.Montana;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.IOException;

/**
 *
 * @author aleja
 */
public class GameWindow extends javax.swing.JFrame implements GraphicContainer{
    
    private Montana montana;
        
    public GameWindow(Montana montana) {
        this.montana = montana;
        initComponents();
    }
    
    private void exitGame(){
        System.exit(0);
    }
    
    public void setMontana(Montana montana) {
        this.montana = montana;
    }

    @Override
    public void paint(Graphics g) {
       super.paint(g); 
       montana.paint(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch(evt.getKeyCode())
        {   
            case KeyEvent.VK_P:
                try {
                    montana.handleKey(evt);
                } catch (IOException e) {
                    System.out.println("Error obteniendo informacion del archivo");
                }
                
            break;

            case KeyEvent.VK_M:
                try {
                    montana.handleKey(evt);
                } catch (IOException e) {
                    System.out.println("Error obteniendo informacion del archivo");
                }
                
            break;

            
            case KeyEvent.VK_Q:
                exitGame();
            break;
            
            case KeyEvent.VK_S:
                try {
                    montana.handleKey(evt);
                } catch (IOException e) {
                    System.out.println("Error obteniendo informacion del archivo");
                }

                
            
            case KeyEvent.VK_SPACE:
                try {
                    montana.handleKey(evt);
                    System.out.println((String.valueOf(this.montana.getPuntaje())));
                } catch (IOException e) {
                    System.out.println("Error obteniendo informacion del archivo");
                }

                
        }
        
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int x = evt.getX();
            int y = evt.getY();
            try{
                this.montana.asesinarPulgasPulguipium(evt.getX(), evt.getY());;
                System.out.println((String.valueOf(this.montana.getPuntaje())));
            } catch (IOException ev){
                System.out.println("Error obteniendo informacion del archivo");
            }
            
        }
        refresh();
    }//GEN-LAST:event_formMouseClicked

    @Override
    public void refresh() {
        this.repaint();
    }

    @Override
    public Rectangle getBoundaries() {
        return this.getBounds();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
